name = "autodiff"
version = "0.1.0"
testDriver = "Test"
defaultTargets = ["benchmark"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "Autodiff"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "benchmark"
root = "Main"
supportInterpreter = true
allowImportAll = true